### ISSUE TITLE
generate-programs-index finds wrong attrPath for "dig" binary

### ISSUE THREAD

**Issue by delroth** [NixOS/nixos-channel-scripts#26]
```
sqlite> select * from Programs where name = "dig";
dig|x86_64-linux|bind
```

Which is technically correct: `dig` is part of the `bind` derivation, but not in its default output. Instead, it's part of the `dnsutils` output which does not get installed by a simple `nix-shell -p bind` (it needs either `nix-shell -p bind.dnsutils` or `nix-shell -p dnsutils` since there is an alias in top-level).

Something somewhere in generate-programs-index should probably be more output-aware, but I lack the ability to easily test changes so this is just an issue report and not a PR :-)

**Comment by brookst** [comment]
This issue seems to be solved now. I get the following:
```
sqlite> select * from Programs where name = "dig";
dig|aarch64-linux|dig
dig|x86_64-linux|dig
```
I'm not sure what fixed this but I ran into a different issue; `tsig-keygen` and `ddns-confgen` are listed as part of the dig package, but are not outputs there. So `command-not-found` erroneously suggested to bring in dig for them, even if it's already enabled.

I'm still trying to find where they actually are and why *they* have the wrong path in `programs.db`.

**Comment by SuperSandro2000** [comment]
dupe of #129713
